== Session
:sectanchors:

=== Mantaining State

Request object are stateless, the request begin when the user broswer open a socket
to the server and ends when the server send the last packet and closes the request.
To maintaint state between requests that come from the same user we need to use *Session*.
Examples :

* session can be used to remember the user that log into the application.
* session can be used in application that are based on the idea of workflow

=== Session Cookie And Url

A Session is some file,memory segment, object managed by the server container,
that contains various data elements. The session is managed only by the server,
the web broswer doesn't hold or maintain this data. To link the brswer request
with the server session  a random ID is used. This ID is generated by the server
on session creatiion and is send back to the broswer. Any  subsequent request
contain the session ID.

Cookiee:: session ID is stored in broswer cookie. After session creation the
server response contains the header `Set-Cookie`.
The cookie can have some attribute like domain, path, max-age, secure-flag, HTTP-only flag.
+
[source,http]
----
Request 1
GET /support HTTP/1.1
Host: www.example.com

Response 1
HTTP/1.1 302 Moved Temporarily
Location: https://www.example.com/support/login
Set-Cookie: JSESSIONID=NRxclGg2vG7kI4MdlLn; Domain=.example.com; Path=/; HttpOnly

Request 2
GET /support/login HTTP/1.1
Host: www.example.com
Cookie: JSESSIONID=NRxclGg2vG7kI4MdlLn

Response 2
HTTP/1.1 200 OK
Content-Type: text/html;charset=UTF-8
Content-Length: 21765

Request 3
POST /support/login HTTP/1.1
Host: www.example.com
Cookie: JSESSIONID=NRxclGg2vG7kI4MdlLn

Response 3
HTTP/1.1 302 Moved Temporarily
Location: http://www.example.com/support/home
Set-Cookie: remusername=Nick; Expires=Wed, 02-Jun-2021 12:15:47 GMT;
Domain=.example.com; Path=/; HttpOnly

Request 4
GET /support/home HTTP/1.1
Host: www.example.com
Cookie: JSESSIONID=NRxclGg2vG7kI4MdlLn; remusername=Nick

Response 4
HTTP/1.1 200 OK
Content-Type: text/html;charset=UTF-8
Content-Length: 56823
----

URL:: The session ID is send back and foward into the URL. The ID is embeded in
every url that the application send back, using the 'Location' header.
+
[source,http]
----
Request 1
GET /support HTTP/1.1
Host: www.example.com

Response 1
HTTP/1.1 302 Moved Temporarily
Location: https://www.example.com/support/login;JSESSIONID=NRxclGg2vG7kI4MdlLn

Request 2
GET /support/login;JSESSIONID=NRxclGg2vG7kI4MdlLn HTTP/1.1
Host: www.example.com

Response 2
HTTP/1.1 200 OK
Content-Type: text/html;charset=UTF-8
Content-Length: 21796
...
<form action="http://www.example.com/support/login;JSESSIONID=NRxclGg2vG7kI4MdlLn"
method="post">
...

Request 3
POST /support/login;JSESSIONID=NRxclGg2vG7kI4MdlLn HTTP/1.1
Host: www.example.com
Response 3
HTTP/1.1 302 Moved Temporarily
Location: http://www.example.com/support/home;JSESSIONID=NRxclGg2vG7kI4MdlLn

Request 4
GET /support/home;JSESSIONID=NRxclGg2vG7kI4MdlLn HTTP/1.1
Host: www.example.com

Response 4
HTTP/1.1 200 OK
Content-Type: text/html;charset=UTF-8
Content-Length: 56854
...
<a href="http://www.example.com/support/somewhere;JSESSIONID=NRxclGg2vG7kI4MdlLn">
----

=== Session Vulnerabilities

The session come with its vulnerabilities:

Copy and Paste Mistake:: The source of this problem is the session ID into the URL.
Session Fixation:: An attacker might go to some web site that acept sessionID
into the URL, creating a session and copy an paste this url in forum or email.
Solution: disable SessionID in URL and change sessionID on log-in.
Cross-Site Scripting and Session Hijacking:: An attacker inject some script into
a site and stoles the user sessionID with `document.cookie`.
Insecure Cookie:: this vulnerability should consider MitM attack.

=== Configuring Session

Session can be configured in *web.xml* using:

* `<session-config>`
** `<session-timeout>`:  haw long in minute session can remain inactive
** `<cookie-config>`: configures session cookie
*** `<name>`
*** `<domain>`
*** `<path>`
*** `<comment>`
*** `<http-only>`: no in javascript cookie
*** `<secure>`: only over HTTPS
*** `<max-age>`: duration time in minutes

** `<tracking-mod>`: add in JavaEE 6 configure the tracking mode,(URL,COOKIE,SSL)
