#  ############################################################################# #
#  Author       : dmike
#  Date         : 2,October 2016
#  Description  : Principal Make file
#
#  Default KBUILD file that does not define only the language variable.
#  Setting it to 'cc'.
#
#  ############################################################################# #
languages := packages
mode := color_
debug := @

src_root := $(root)/packs
dep_root := $(empty)

#  ############################################################################# #
#  Command definition.
#  ############################################################################# #
CC := gcc
LD := ld
RM := rm
MKDIR:= mkdir
AR:= ar
RANLIB:= ranlib
DOCKER:= docker
GIT:= git
GO:= go

export CC LD RM MKDIR AR RANLIB DOCKER GIT GO